edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
normalize_comments = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
format_macro_definitions = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_granularity = "Module"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
use_field_init_shorthand = false
use_try_shorthand = false
use_explicit_maybe_uninit = false
license_template_path = ""
format_code_in_doc_comments = true
format_doc_comments = true
doc_comment_code_block_width = 80
wrap_comments = false
comment_width = 80
normalize_doc_attributes = false
format_macro_rewrites = true
format_generated_files = false
format_strings = true
indent_style = "Block"
overflow_delimited_expr = false
struct_lit_width = 18
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_arm_leading_pipes = "Never"
match_arm_blocks = "Block"
empty_block_style = "ClosedBrace"
chain_width = 80
single_line_if_else_max_width = 50
wrap_attributes = false
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.0"
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
report_unsafe = "Unnumbered"
ignore = []
merge_imports = true
imports_indent = "Block"
imports_layout = "Mixed"
group_imports = "StdExternalCrate"
reorder_imports = true

